import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import CanvasWrapper from "@/context/CanvasWrapper";

const Mont = Montserrat({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Mont.className} antialiased flex`}>
        <CanvasWrapper>{children}</CanvasWrapper>
      </body>
    </html>
  );
}
